# ========== BASE DE DONNEES ==========
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/correcteur_etudiant_v2
spring.datasource.username=postgres
spring.datasource.password=Rota
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== APPLICATION ==========
spring.application.name=correcteur_etudiant_v2
server.port=8080

